default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: nabeel

development:
  <<: *default
  database: hello_rails_react_development

test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_react_test
  pool: 5
  username: postgres
  password: nabeel

  staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
